#! /bin/sh

# trick qt apps to use gtk icon theme
#export DESKTOP_SESSION=gnome

sxhkd &
xrdb -merge $HOME/.Xresources
# neutral pointer
xsetroot -cursor_name left_ptr &
# key refresh rate
xset r rate 320 35
# mouse acceleration
xset m 3/2 6
# keyboard layouts switch
setxkbmap  -layout "us,ru" -option "grp:alt_space_toggle,grp_led:scroll"


#bspc monitor HDMI-1 -f -d I II III IV V VI VII VIII IX X
#bspc monitor "HDMI-1" -f -d 一 二 三 四 五 六 七 八 九 十
bspc monitor "eDP-1" -d left
bspc monitor "HDMI-1" -f -d one two three four five six seven eight nine ten
bspc monitor "DP-1" -d right

background=$(xrdb -query | grep "background" | cut -f2 | sed -r 's/#//' | head -n 1)
foreground=$(xrdb -query | grep "foreground" | cut -f2 | sed -r 's/#//' | head -n 1)
color0=$(xrdb -query | grep "color0" | cut -f2 | sed -r 's/#//' | head -n 1)
color1=$(xrdb -query | grep "color1" | cut -f2 | sed -r 's/#//' | head -n 1)
color2=$(xrdb -query | grep "color2" | cut -f2 | sed -r 's/#//' | head -n 1)
color3=$(xrdb -query | grep "color3" | cut -f2 | sed -r 's/#//' | head -n 1)
color4=$(xrdb -query | grep "color4" | cut -f2 | sed -r 's/#//' | head -n 1)
color5=$(xrdb -query | grep "color5" | cut -f2 | sed -r 's/#//' | head -n 1)
color6=$(xrdb -query | grep "color6" | cut -f2 | sed -r 's/#//' | head -n 1)
color7=$(xrdb -query | grep "color7" | cut -f2 | sed -r 's/#//' | head -n 1)
color8=$(xrdb -query | grep "color8" | cut -f2 | sed -r 's/#//' | head -n 1)
color9=$(xrdb -query | grep "color9" | cut -f2 | sed -r 's/#//' | head -n 1)

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config ignore_ewmh_focus           true
bspc config focus_follows_pointer       false
bspc config click_to_focus              button1
bspc config pointer_follows_focus       false
bspc config pointer_follows_monitor     true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

#bspc config normal_border_color         "#$color8"
bspc config active_border_color         "#$color3"
bspc config focused_border_color        "#$color4"
#bspc config presel_feedback_color       "#$color1"

bspc config external_rules_command ~/bin/bspwm_spotify_rule

bspc rule -a Firefox desktop='one'
bspc rule -a Thunderbird desktop='two'
bspc rule -a Skype desktop='two' focus=on follow=on
bspc rule -a Sublime_text desktop='four' focus=on follow=on
bspc rule -a vlc desktop='left' state=floating focus=on follow=on
bspc rule -a Tilix desktop='right' focus=on
bspc rule -a streamlink-twitch-gui desktop='six' state=floating focus=on follow=on
bspc rule -a feh state=floating
bspc rule -a Nautilus state=floating focus=on
bspc rule -a Pavucontrol state=floating focus=on
bspc rule -a Lxappearance state=floating focus=on
bspc rule -a Wireshark desktop='ten' focus=on follow=on
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Steam state=floating desktop='three'
bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Panel
# Terminate already running bar instances
killall -q polybar
# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
# Launch bar1 and bar2
polybar top &

# autostart applications
feh --no-fehbg --bg-fill $HOME/Downloads/gvbs329bd0z01.jpg &
compton --respect-prop-shadow &
clipit &
nm-applet &

firefox &
thunderbird &
skypeforlinux &
