#! /bin/sh

#bspc monitor -d shell web chat dev games media

for monitor in $(bspc query -M); do
	bspc monitor $monitor -d shell web chat dev games media
done

bspc config border_width        2
bspc config window_gap          12
bspc config split_ratio         0.52

bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config apply_floating_atom    true
bspc config history_aware_focus    true
bspc config ignore_ewmh_focus      true

#bspc config focus_follows_pointer true
bspc config auto_alternate true
#bspc config auto_cancel true

bspc rule -a Firefox desktop=^2
bspc rule -a vlc desktop=^6 follow=on
bspc rule -a gmrun follow=on
bspc rule -a Nautilus floating=on
bspc rule -a Skype desktop=^3 floating=on
bspc rule -a transmission-gtk desktop=^6 follow=on floating=on
bspc rule -a feh floating=on
bspc rule -a Steam desktop=^5 fullscreen=on

bspwm_colors
reloadpanel
reloadwallpaper

compton -b
