#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

bspc config top_padding $PANEL_HEIGHT
bspc control --put-status
volume status &
#bright status &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
#clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &
clock -s -i 5 -f 'C%A %H:%M' > "$PANEL_FIFO" &
essid -s -i 3 -f 'N%s' > "$PANEL_FIFO" &
battery -s -i 11 -f 'B%s %i' > "$PANEL_FIFO" 2> /dev/null &
dropbox_status > "$PANEL_FIFO" &

PANEL_FONT_FAMILY='DejaVu Sans'
PANEL_FONT_SIZE=12
PANEL_ICONS_FONT_FAMILY=SimpleIcons
PANEL_ICONS_FONT_SIZE=16

. panel_colors
PANEL_HEIGHT=24
cat "$PANEL_FIFO" | panel_dzen2 -f "$PANEL_FONT_FAMILY" -s "$PANEL_FONT_SIZE" -F "$PANEL_ICONS_FONT_FAMILY" -S "$PANEL_ICONS_FONT_SIZE" | uq | dzen2 -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "${PANEL_FONT_FAMILY}:pixelsize=${PANEL_FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" &

wait
